// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB48hJx0D4s_n5-5GplcLX-MzKi_NCc4Wg',
    appId: '1:818496104677:web:94cea1cc0a2e79e9f0cc0c',
    messagingSenderId: '818496104677',
    projectId: 'wechat-d43c1',
    authDomain: 'wechat-d43c1.firebaseapp.com',
    storageBucket: 'wechat-d43c1.appspot.com',
    measurementId: 'G-BC3B9B70MK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnjpJBY2M2h2F3D9FfYtcmqRsiLjNseG0',
    appId: '1:818496104677:android:924a542a15c58441f0cc0c',
    messagingSenderId: '818496104677',
    projectId: 'wechat-d43c1',
    storageBucket: 'wechat-d43c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_0zVgqe1sYzFK9apYgrPCNEkD2zg7Hok',
    appId: '1:818496104677:ios:09305f139d337164f0cc0c',
    messagingSenderId: '818496104677',
    projectId: 'wechat-d43c1',
    storageBucket: 'wechat-d43c1.appspot.com',
    iosClientId: '818496104677-6a5umno9m144h940sabm54npl8ov74cj.apps.googleusercontent.com',
    iosBundleId: 'com.example.wechat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_0zVgqe1sYzFK9apYgrPCNEkD2zg7Hok',
    appId: '1:818496104677:ios:09305f139d337164f0cc0c',
    messagingSenderId: '818496104677',
    projectId: 'wechat-d43c1',
    storageBucket: 'wechat-d43c1.appspot.com',
    iosClientId: '818496104677-6a5umno9m144h940sabm54npl8ov74cj.apps.googleusercontent.com',
    iosBundleId: 'com.example.wechat',
  );
}
